// <auto-generated />
using System;
using CentralStore.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralStore.Migrations
{
    [DbContext(typeof(CentralStoreDbContext))]
    [Migration("20260320135157_AddedCustomersToDb")]
    partial class AddedCustomersToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentralStore.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f1a6c9e-2c4b-4a6d-9c7f-1e5a2b3d4c11"),
                            ConcurrencyToken = new Guid("a3b9d2f1-6e7c-4b8a-9f01-2d3c4e5f6a77"),
                            CreatedAt = new DateTime(2024, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.petrova@example.com",
                            FirstName = "Maria",
                            LastName = "Petrova",
                            Password = "Password123",
                            StoreId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedAt = new DateTime(2024, 2, 2, 11, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1c7d9e4a-5b6f-4a2e-8c3d-7f9a1b2c3d44"),
                            ConcurrencyToken = new Guid("c5e8f1a2-3d4b-4f6a-8c9e-0b1a2d3f4e55"),
                            CreatedAt = new DateTime(2024, 2, 5, 9, 15, 0, 0, DateTimeKind.Utc),
                            Email = "ivan.georgiev@example.com",
                            FirstName = "Ivan",
                            LastName = "Georgiev",
                            Password = "Password123",
                            StoreId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedAt = new DateTime(2024, 2, 6, 10, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7a2e5c1d-9b3f-4c6a-8d1e-2f3a4b5c6d66"),
                            ConcurrencyToken = new Guid("d7f2a3b4-5c6d-4e7f-9a0b-1c2d3e4f5a66"),
                            CreatedAt = new DateTime(2024, 2, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.dimitrova@example.com",
                            FirstName = "Elena",
                            LastName = "Dimitrova",
                            Password = "Password123",
                            StoreId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedAt = new DateTime(2024, 2, 11, 15, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3b4c5d6e-7f8a-4b1c-9d2e-6f7a8b9c0d77"),
                            ConcurrencyToken = new Guid("e9a1b2c3-d4e5-4f6a-8b9c-0d1e2f3a4b77"),
                            CreatedAt = new DateTime(2024, 2, 15, 8, 45, 0, 0, DateTimeKind.Utc),
                            Email = "georgi.ivanov@example.com",
                            FirstName = "Georgi",
                            LastName = "Ivanov",
                            Password = "Password123",
                            StoreId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedAt = new DateTime(2024, 2, 16, 9, 55, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CentralStore.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a8c30a4-0445-4b1f-b01c-4a5c8f4d832f"),
                            ConcurrencyToken = new Guid("bfe2f7fd-3551-4d13-9fcd-d0c1bebafd00"),
                            CreatedAt = new DateTime(2024, 1, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Large solid maple conference table with integrated cable troughs.",
                            MinPrice = 1299.99m,
                            Name = "Aurora Conference Table",
                            Price = 1399.99m,
                            StoreId = new Guid("0d9f1b3c-6d45-4a2d-ae2f-8d253b1ecf1d"),
                            UpdatedAt = new DateTime(2024, 1, 4, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2f5d93e7-1b60-4687-9baa-c2aa1c5dc65a"),
                            ConcurrencyToken = new Guid("75cbf198-7ffb-4ee2-9b26-17fa16cbd59e"),
                            CreatedAt = new DateTime(2024, 1, 5, 13, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic lounge chair upholstered in perforated leather.",
                            MinPrice = 599.00m,
                            Name = "Lumen Lounge Chair",
                            Price = 649.50m,
                            StoreId = new Guid("0d9f1b3c-6d45-4a2d-ae2f-8d253b1ecf1d"),
                            UpdatedAt = new DateTime(2024, 1, 5, 16, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3662d4ac-1a6f-447d-80b0-4673c7c7fc56"),
                            ConcurrencyToken = new Guid("8f6e54f6-4ab9-40b3-8592-7c5d0d4d1a2e"),
                            CreatedAt = new DateTime(2024, 1, 6, 9, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Height-adjustable standing desk with waterfall edge and programmable presets.",
                            MinPrice = 899.95m,
                            Name = "Northwind Standing Desk",
                            Price = 999.95m,
                            StoreId = new Guid("4c8a7f40-5bf5-4e39-90e3-6c8b5c8aa940"),
                            UpdatedAt = new DateTime(2024, 1, 6, 9, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4442e177-f6ea-4b77-9f07-4f44d7f1b137"),
                            ConcurrencyToken = new Guid("3d54c37c-61b9-4139-a6ab-149226c95ebb"),
                            CreatedAt = new DateTime(2024, 1, 7, 7, 10, 0, 0, DateTimeKind.Utc),
                            Description = "LED task lamp offering tunable white light and touch dimming.",
                            MinPrice = 109.99m,
                            Name = "Solstice Task Lamp",
                            Price = 129.99m,
                            StoreId = new Guid("4c8a7f40-5bf5-4e39-90e3-6c8b5c8aa940"),
                            UpdatedAt = new DateTime(2024, 1, 7, 7, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5bacb48d-43d6-4f06-9cf8-16c1f8be6b66"),
                            ConcurrencyToken = new Guid("97b3f65a-099e-4a6e-bfd8-1c3e679a5b87"),
                            CreatedAt = new DateTime(2024, 1, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modular reception sofa with antimicrobial fabric.",
                            MinPrice = 1799.00m,
                            Name = "Vela Reception Sofa",
                            Price = 1899.00m,
                            StoreId = new Guid("8f7da5a1-22b6-4b7a-aa55-c38e1dfb0d1c"),
                            UpdatedAt = new DateTime(2024, 1, 9, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("686b45f0-cb33-4d03-b040-6a8d966b0f29"),
                            ConcurrencyToken = new Guid("a6d4eed6-9e7b-4bfa-92c6-2e63a2dc4d5e"),
                            CreatedAt = new DateTime(2024, 1, 10, 11, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Wall-mounted acoustic panel with felt finish.",
                            MinPrice = 229.00m,
                            Name = "Cascade Acoustic Panel",
                            Price = 249.00m,
                            StoreId = new Guid("8f7da5a1-22b6-4b7a-aa55-c38e1dfb0d1c"),
                            UpdatedAt = new DateTime(2024, 1, 10, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77cc8d8e-bfa1-4f4d-b594-0bb9f8ce7a8a"),
                            ConcurrencyToken = new Guid("0c2df9b7-dd68-4e96-8718-ffbb9b5b1a75"),
                            CreatedAt = new DateTime(2024, 1, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Steel mobile pedestal with silent casters and lock.",
                            MinPrice = 349.25m,
                            Name = "Harbor Mobile Pedestal",
                            Price = 379.25m,
                            StoreId = new Guid("0d9f1b3c-6d45-4a2d-ae2f-8d253b1ecf1d"),
                            UpdatedAt = new DateTime(2024, 1, 12, 15, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8237c4d1-2805-4f65-9c37-18452f2fe14b"),
                            ConcurrencyToken = new Guid("bd6c731f-5083-4bed-8f36-54d4efbf8f90"),
                            CreatedAt = new DateTime(2024, 1, 13, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "High-back executive chair with synchronous tilt and leather.",
                            MinPrice = 749.99m,
                            Name = "Mercury Executive Chair",
                            Price = 799.99m,
                            StoreId = new Guid("4c8a7f40-5bf5-4e39-90e3-6c8b5c8aa940"),
                            UpdatedAt = new DateTime(2024, 1, 13, 10, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("92ea71b4-6f7b-4c76-a0bf-aee9871d2a78"),
                            ConcurrencyToken = new Guid("65e5a1b6-0b25-4de1-b61f-11cad0ff6a47"),
                            CreatedAt = new DateTime(2024, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modular shelving system with powder-coated frames.",
                            MinPrice = 429.75m,
                            Name = "Zenith Modular Shelf",
                            Price = 459.75m,
                            StoreId = new Guid("8f7da5a1-22b6-4b7a-aa55-c38e1dfb0d1c"),
                            UpdatedAt = new DateTime(2024, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a240d279-c935-4392-becf-2eceaab4e52d"),
                            ConcurrencyToken = new Guid("f6ef3101-2c4d-4b31-8b6a-f5f2f5f55df5"),
                            CreatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Magnetic dry-erase board with aluminum frame.",
                            MinPrice = 199.99m,
                            Name = "Vertex Whiteboard",
                            Price = 219.99m,
                            StoreId = new Guid("4c8a7f40-5bf5-4e39-90e3-6c8b5c8aa940"),
                            UpdatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b15f8d50-4c37-4f84-876d-2a9799c8b106"),
                            ConcurrencyToken = new Guid("7ca0a5de-6e7b-4efd-8e52-8b77b2c571f3"),
                            CreatedAt = new DateTime(2024, 1, 16, 8, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Glass phone booth with integrated ventilation.",
                            MinPrice = 4599.00m,
                            Name = "Nimbus Phone Booth",
                            Price = 4999.00m,
                            StoreId = new Guid("1f2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            UpdatedAt = new DateTime(2024, 1, 16, 8, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c0d3b144-e0b9-4acd-ab33-98d2cf7b8e2c"),
                            ConcurrencyToken = new Guid("21b58d9d-4c27-46c9-8f2c-0c3a5011d8d2"),
                            CreatedAt = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secure storage cabinet with programmable keypad lock.",
                            MinPrice = 1199.00m,
                            Name = "Atlas Storage Cabinet",
                            Price = 1249.00m,
                            StoreId = new Guid("1f2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            UpdatedAt = new DateTime(2024, 1, 17, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1c6db53-89a4-457e-8d4d-08e4d2bff723"),
                            ConcurrencyToken = new Guid("d272ea1f-4b6b-48dd-95a5-ff4fb9c5d430"),
                            CreatedAt = new DateTime(2024, 1, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable-height bar stool with swivel base.",
                            MinPrice = 259.95m,
                            Name = "Harbor Bar Stool",
                            Price = 279.95m,
                            StoreId = new Guid("0d9f1b3c-6d45-4a2d-ae2f-8d253b1ecf1d"),
                            UpdatedAt = new DateTime(2024, 1, 18, 10, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e25f330e-adc1-4144-976a-8a39633c7a7f"),
                            ConcurrencyToken = new Guid("93d9d2c3-9f4a-4c0b-bb7c-c3b8ba0fdc6d"),
                            CreatedAt = new DateTime(2024, 1, 19, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dual monitor arm with gas spring and cable management.",
                            MinPrice = 429.50m,
                            Name = "Helios Monitor Arm",
                            Price = 459.50m,
                            StoreId = new Guid("1f2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            UpdatedAt = new DateTime(2024, 1, 19, 11, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fadf2e08-250e-4a55-8a27-8c7b902c5d99"),
                            ConcurrencyToken = new Guid("d7a96e1e-0c1b-4c0d-b6f1-0fcf8c2cf091"),
                            CreatedAt = new DateTime(2024, 1, 20, 8, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Personal sound masking fixture with warm light.",
                            MinPrice = 309.00m,
                            Name = "Comet Sound Mask",
                            Price = 329.00m,
                            StoreId = new Guid("8f7da5a1-22b6-4b7a-aa55-c38e1dfb0d1c"),
                            UpdatedAt = new DateTime(2024, 1, 20, 8, 20, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
